### PR TITLE
const'ify some parameters

### PR DESCRIPTION
**Pull request by namreeb**
This resolves issue #22

### CODE REVIEW

**Comment by namreeb** [comment]
With the recent activity I'm wondering why this is being skipped over?

**Comment by kokke** [comment]
Hi @namreeb,

Thanks for your interest in my project, and I'm sorry for not commenting on your ticket sooner!

I am saving this change for a larger code change, that will encompass some of the bug fixes mentioned in other pull-requests/issues and is fixed in various ways by forkers of this project. Another fix I would like to add together with merging this change, is a change in the CBC-code, so that it operates completely on the output-buffer, so you could const'ify those params as well.
These are the same reasons I'm keeping your issue+pull-request open :)

I spend a lot more time reviewing and pondering issues that require changes to the code..

**Comment by kokke** [comment]
This issue e.g.: https://github.com/kokke/tiny-AES128-C/pull/12 also just requires deleting/commenting out a lot of code - but I am leaving that open for the same reasons :)

**Comment by namreeb** [comment]
Thank you for your reply.  I would selfishly request that you merge this one sooner rather than later so I can remove the const_cast<>s in my code :)

**Comment by kokke** [comment]
There we go.

**Pull request merged**
